name: weather_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  http: ^0.13.6
  connectivity_plus: ^2.3.4
  internet_connection_checker_plus: ^1.0.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
